In [2]:
import torch
import numpy as np

In [3]:
# tensors can create directly from data
data = [[1,2], [3,4]] # this is python list
x_data = torch.tensor(data)

# or from np array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# or from another tensor
x_ones = torch.ones_like(x_data) # retains the properties(whaht is props?) of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float) # "dtype=torch.float" is prop so we can override

# with random or constant
shape = (2,3) # => it's a tuple
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

#tensor attributes: look torch.tensor class

In [4]:
#tensor operations

tensor = torch.rand((3,3))

# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")
    
# join tensors with cat, given dimention
t1 = torch.cat([tensor, tensor, tensor], dim=1)

Device tensor is stored on: cuda:0


In [5]:
# indexing and slicing
tensor = torch.ones(4, 4)
tensor[:,1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [7]:
# element-wise multiplying
tensor.mul(tensor)
# matrix multipication
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [10]:
# change to numpy array. tensor and np array share same underlying memory locations
t = torch.ones(5)
t = t.numpy
t

<function Tensor.numpy>

In [12]:
#from numpy to tensor
n = np.ones(5)
t = torch.from_numpy(n)
t


tensor([1., 1., 1., 1., 1.], dtype=torch.float64)